{
  "showDialog": true,
  "latestVersionCode": 3.11.1,
  "latestVersionName": "1.1",
  "title": "UPDATE AVAILABLE",
  "message": "Get the newest features and improvements.",
  "UpdateButtonText": "DOWNLOAD",
  "UpdateButtonUrl": "https://shortxlinks.in/iwAbL"
}
